name: AWS S3 Bucket CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  tfsec:
    uses: ./.github/workflows/tfsec.yml

  terraform-ci:
    runs-on: ubuntu-latest
    needs: tfsec

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Terraform init
      run: terraform init
  
    - name: Run TFSec
      run: tfsec --config-file tfsec.yml

    - name: Run TFLint
      run: tflint

    - name: Terraform Plan
      run: terraform plan

  terraform-cd:
    runs-on: ubuntu-latest
    needs: terraform-ci
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Terraform Apply
      run: terraform apply --auto-approve
