name: AWS S3 Bucket CI/CD

on:
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${ secrets.AWS_ACCESS_KEY_ID }
  AWS_SECRET_ACCESS_KEY: ${ secrets.AWS_SECRET_ACCESS_KEY }
  AWS_REGION : "us-east-1"

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

  terraform-ci:
    runs-on: ubuntu-latest
    needs: tfsec

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Run TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest
        run: tflint
    
    - name: Terraform init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

  terraform-cd:
    runs-on: ubuntu-latest
    needs: terraform-ci

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Terraform Apply
      run: terraform apply --auto-approve
