name: AWS S3 Bucket CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

  terraform-ci:
    runs-on: ubuntu-latest
    needs: tfsec

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Terraform init
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest
        run: terraform init
        

    - name: Run TFLint
      run: tflint

    - name: Terraform Plan
      run: terraform plan

  terraform-cd:
    runs-on: ubuntu-latest
    needs: terraform-ci

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Terraform Apply
      run: terraform apply --auto-approve
